[package]
name = "swap-serde"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
data-encoding = { workspace = true }
libp2p = { workspace = true }
monero-address = { workspace = true }
monero-oxide-ext = { path = "../monero-oxide-ext" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
