[package]
name = "swap-proptest"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { workspace = true }
ecdsa_fun = { workspace = true }
proptest = "1"
tokio = { workspace = true }

[lints]
workspace = true
