[package]
name = "eigenweb-pinning"
version = "0.1.0"
edition = "2021"

[features]
default = ["memory"]
memory = []

[dependencies]
# Libp2p dependencies
libp2p = { workspace = true, features = ["cbor", "request-response", "macros"] }
libp2p-identity = { workspace = true, features = ["serde"] }
swap-p2p = { path = "../../swap-p2p" }

# Serialization
bytes = { version = "1.5", features = ["serde"] }
serde = { workspace = true }
serde_cbor = "0.11"

# Crypo
sha2 = "0.10"

backoff = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
atty = "0.2"
libp2p = { workspace = true, features = ["cbor", "request-response", "macros", "tcp", "noise", "yamux", "tokio"] }
libp2p-tor = { path = "../../libp2p-tor", features = ["listen-onion-service"] }
tokio = { workspace = true, features = ["io-std", "io-util"] }
tor-hsservice = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
