[package]
name = "orangefren_client"
version = "0.1.0"
edition = "2024"

[dependencies]
generated-client = { path = "../generated-client" }
monero = { workspace = true }
serde = { workspace = true }
typeshare = { workspace = true }
swap-serde = { path = "../../swap-serde" }
thiserror = { workspace = true }
bitcoin = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-stream = "0.1.17"
reqwest = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
